[package]
name = "bfc-lexer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "a brainfuck lexer"

[dependencies]
nom.workspace = true

[lints]
workspace = true
